# NUMPY

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
e = np.array([[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]])
print(e.ndim)

4


In [6]:
a  = np.array([1,2,3,4,5])
np.save('outfile',a)

In [7]:
ls

 Volume in drive C is Windows
 Volume Serial Number is C4CC-83E1

 Directory of C:\Users\Sap\Internship_144\Python Fundamental Crash Course

17-01-2024  12:21    <DIR>          .
16-01-2024  14:23    <DIR>          ..
17-01-2024  12:11    <DIR>          .ipynb_checkpoints
17-01-2024  12:01             7,490 EXERCISE-1.ipynb
17-01-2024  12:21             2,114 NUMPY.ipynb
17-01-2024  12:21               148 outfile.npy
17-01-2024  11:04             9,834 Python Fundamentals - For beignners.ipynb
               4 File(s)         19,586 bytes
               3 Dir(s)  383,715,463,168 bytes free


In [8]:
cat

NameError: name 'cat' is not defined

In [9]:
b = np.load('outfile.npy')
print(b)

[1 2 3 4 5]


In [6]:
import numpy as np
arr = np.arange(12).reshape(2,2,3)
print(arr)
print(arr[:1,:1])
print(arr[:1,0:,:1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1 2]]]
[[[0]
  [3]]]
