# PANDAS

In [5]:
import pandas as pd
import numpy as np

In [7]:
sr = pd.Series()
print(sr)
data = np.array(['g','t','h','t','h','t'])
sr = pd.Series(data)
print(sr)

Series([], dtype: float64)
0    g
1    t
2    h
3    t
4    h
5    t
dtype: object


C:\Users\Sap\AppData\Local\Temp\ipykernel_7508\3795388741.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  sr = pd.Series()


In [16]:
a = np.arange(12).reshape(3,4)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
b = pd.DataFrame(a)
print(b)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [19]:
data = { 'Name': ['Tom', 'nick', 'krish', 'jack'], 
        'Age': [20, 21, 19, 18]}
df = pd.DataFrame(data)
display(df)

Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [22]:
info = pd.DataFrame({"P":[4, 7, 1, 8, 9], 
                     "Q":[6, 8, 10, 15, 11], 
                     "R":[17, 13, 12, 16, 14], 
                     "S":[15, 19, 7, 21, 9]}, 
                    index =["Parker", "William", "Smith", "Terry", "Phill"])
info

P   Q   R   S
Parker   4   6  17  15
William  7   8  13  19
Smith    1  10  12   7
Terry    8  15  16  21
Phill    9  11  14   9

In [25]:
marks = pd.DataFrame({"Physics":[75,55,85,95],
                      "maths":[77,55,64,51],
                      "chemistry":[45,65,66,85]},
                     index = ["Arun","Mehar","Kachroo","sameer"])
marks

Physics  maths  chemistry
Arun          75     77         45
Mehar         55     55         65
Kachroo       85     64         66
sameer        95     51         85

In [26]:
marks.reindex(['A','B','C'])

Physics  maths  chemistry
A      NaN    NaN        NaN
B      NaN    NaN        NaN
C      NaN    NaN        NaN

In [33]:
marks.reindex(['A','B','C'], fill_value = 100)

Physics  maths  chemistry
A      100    100        100
B      100    100        100
C      100    100        100

In [39]:
unsorted_df = pd.DataFrame(np.array([[1,2],[6,8],[7,2],[3,8],[9,1]]), index= [1,4,5,2,3], columns = ['co12', 'col1'])
sorted_df = unsorted_df.sort_index() 
print (sorted_df)

   co12  col1
1     1     2
2     3     8
3     9     1
4     6     8
5     7     2


In [46]:
unsorted_df = pd.DataFrame(np.array([[1,2],[6,8],[7,2],[3,8],[9,1]]), index= [1,4,5,2,3], columns = ['col2', 'col1'])
sorted_df=unsorted_df.sort_index(axis=1)
print (sorted_df)

   col1  col2
1     2     1
4     8     6
5     2     7
2     8     3
3     1     9


In [43]:
s = pd.Series(['Tom', 'William Rick', 'John', 'Alber@t', np.nan, '1234', 'SteveSmith'])
print (s. str.lower())

0             tom
1    william rick
2            john
3         alber@t
4             NaN
5            1234
6      stevesmith
dtype: object


In [44]:
s = pd.Series(['Tom', 'William Rick', 'John', 'Alber@t', np.nan, '1234', 'SteveSmith'])
print (s. str.islower())

0    False
1    False
2    False
3    False
4      NaN
5    False
6    False
dtype: object
